MOMO 21 add loading screen
Momo-66/Momo pull request #8
Opened 2023-02-18 04:45 UTC by onmay16

* 로딩 gif 이미지 임의로 사용하였습니다. 전달 후 교체 예정.
* 로딩 시간 또한 임의로 3초로 설정했습니다. 전달 받은 로딩 gif duration에 따라 수정 예정.
* prettier 때문에 `LoadingScreen.js` 내 불필요한 수정 사항 있을 수 있습니다.

**질문!** @JDhyeok @corea2244 
다들 js 파일 작성할 때 prettier 오류 안 뜨시는지요?
프로젝트 내 설정 때문인지, 제 로컬 vscode 설정 때문인지 확실하지 않아서 여쭤봅니다.
후자라면... 빠른 시일 내에 설정 바꿔 보도록 하겠습니다. 💦

2023-02-18 15:59 UTC, JDhyeok requested changes
IMHO

2023-02-18 15:59 UTC, JDhyeok commented on src/screens/LoginScreen.js
> +import LoadingScreen from './LoadingScreen';
로딩화면을 `LoginScreen.js`에서 추가하는 것 보다는 `App.js` 혹은 `RootNavigator.js` 에서 사용하는 건 어떨까요

회원가입/로그인한 이후 다시 접속할 때 로그인 없이 바로 MainScreen으로 갈텐데 메인화면에도 로딩화면을 설정을 해줘야 한다는 점 때문에 추후 코드중복이 있을 것 같습니다.

따라서 LoginScreen진입점 보다 상위 파일에서 로딩화면이 있으면 좋을 것 같습니다. 👍🏻

2023-02-18 16:00 UTC, JDhyeok commented on src/screens/LoginScreen.js
> +  useEffect(() => {
LGTM

2023-02-18 16:01 UTC, JDhyeok commented
Prettier 오류는 어떤 오류인가요? 공유해주시면 같이 찾아보겠습니다. :)

2023-02-18 21:08 UTC, onmay16 commented
> @onmay16 Prettier 오류는 어떤 오류인가요? 공유해주시면 같이 찾아보겠습니다. :)

![image](https://user-images.githubusercontent.com/87830290/219899407-249e51c3-c675-420b-bbba-e1158800eb86.png)
포맷팅 관련 오류들인데 이런 식으로 아주 자잘한 부분까지 뜨더라구요.
![image](https://user-images.githubusercontent.com/87830290/219899495-19c16f19-ff84-41da-9d8d-7fc73b15e0c5.png)
물론 고치지 않아도 정상 작동하긴 하지만 실직적으로 작동에 지장을 주는 오류들을 확인해야 할 때 꽤 거슬리네요 🙃...

2023-02-18 21:24 UTC, onmay16 commented on src/screens/LoginScreen.js
> +import LoadingScreen from './LoadingScreen';
로그인 된 이후의 경우를 생각하지 못했네요. 해당 부분 `App.js`로 이동하였습니다. Good call!
그리고 Redux에 로그인 상태 구현 후에는 현재 임시로 사용 중인 `loading` 상태를 로그인 상태에 따라 설정될 수 있도록 바꿔야 할 것 같습니다.

2023-02-19 02:34 UTC, JDhyeok approved these changes

2023-02-19 02:36 UTC, JDhyeok commented
LGTM

2023-02-19 02:37 UTC, merged